-- ============================================================
-- Schema PostgreSQL do Railway
-- ============================================================

-- Clientes (um registro por número de WhatsApp)
CREATE TABLE IF NOT EXISTS customers (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone      TEXT UNIQUE NOT NULL,
  name       TEXT,
  email      TEXT,
  lang       TEXT NOT NULL DEFAULT 'pt',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Pedidos
--
-- items_json carrega os modificadores por item:
--   { id, name, nomeCozinha, qty, price, removed[], added[], choices[] }
-- O preço gravado aqui é o que o código calculou de config/menu.json e
-- config/ingredientes.json — nunca o que a conversa produziu.
CREATE TABLE IF NOT EXISTS orders (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   BIGINT REFERENCES customers(id),
  phone         TEXT NOT NULL,
  lang          TEXT NOT NULL DEFAULT 'pt',
  items_json    JSONB NOT NULL,
  order_type    TEXT NOT NULL DEFAULT 'delivery',
  customer_name TEXT,
  city          TEXT NOT NULL,
  address       TEXT NOT NULL,
  subtotal      NUMERIC(10,2) NOT NULL,
  delivery_fee  NUMERIC(10,2) NOT NULL,
  total         NUMERIC(10,2) NOT NULL,
  status        TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'awaiting_review', 'paid', 'printed',
                                  'delivered', 'rejected', 'cancelled')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Reserva curta da impressão. O pedido continua `paid` até o aparelho
-- confirmar que os bytes chegaram à impressora; se o celular cair, a reserva
-- expira e a comanda volta sozinha para a fila.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS print_claim_token_hash TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS print_claim_device TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS print_claimed_at TIMESTAMPTZ;

-- Fluxo do status, e por que ele importa:
--
--   pending          pedido criado, instrucoes do Zelle enviadas
--   awaiting_review  comprovante chegou, esperando o dono conferir
--   paid             o dono liberou com !liberar  <- unico gatilho da impressao
--   printed          a comanda saiu no papel
--   delivered        entregue
--   rejected         o dono recusou o comprovante
--   cancelled        cancelado antes de pagar
--
-- getNextPrintableOrder() busca status='paid'. Como so o !liberar escreve
-- 'paid', o gate da impressora e um ponto so: comprovante nao confirmado nunca
-- vira comida na chapa. Ver docs/SEGURANCA.md.

-- Pagamentos (Zelle)
--
-- Zelle nao tem webhook nem API de estorno: nada externo confirma o pagamento,
-- e nada desfaz. Por isso a confirmacao e humana e fica registrada aqui — quem
-- liberou e quando.
CREATE TABLE IF NOT EXISTS payments (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id          BIGINT NOT NULL REFERENCES orders(id),
  method            TEXT NOT NULL DEFAULT 'zelle',
  amount            NUMERIC(10,2) NOT NULL,
  status            TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'awaiting_review',
                                      'review_reminded', 'paid', 'rejected')),

  -- Guardamos somente que o comprovante chegou e quando. A imagem é lida em
  -- memória, enviada ao dono pelo WhatsApp e descartada; não existe bucket.
  proof_received_at TIMESTAMPTZ,

  -- Quem liberou. E o registro que transforma "o pedido saiu" em "fulano
  -- mandou sair", e o telefone completo fica so aqui, nunca no papel.
  approved_by       TEXT,
  approved_at       TIMESTAMPTZ,
  rejected_reason   TEXT,

  paid_at           TIMESTAMPTZ
);

-- Estado do bot que precisa sobreviver a um deploy.
-- Hoje guarda `fechado_ate`: quando o dono encerra o atendimento mais cedo
-- pelo WhatsApp (!fechar), o instante da proxima abertura fica aqui.
CREATE TABLE IF NOT EXISTS bot_settings (
  key        TEXT PRIMARY KEY,
  value      TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Itens esgotados. So as excecoes ficam aqui: item ausente esta disponivel.
-- Vale tambem para ingrediente (bacon acabou) — o id e o mesmo do
-- config/ingredientes.json.
CREATE TABLE IF NOT EXISTS item_availability (
  item_id    TEXT PRIMARY KEY,
  available  BOOLEAN NOT NULL DEFAULT true,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Consumo da IA, por dia.
--
-- Em memoria nao serviria: o teto de gasto tem que sobreviver a um restart,
-- senao um deploy no meio de um ataque zera a conta e o teto nunca fecha.
CREATE TABLE IF NOT EXISTS ai_usage (
  dia        DATE PRIMARY KEY,
  chamadas   INT NOT NULL DEFAULT 0,
  tokens_in  BIGINT NOT NULL DEFAULT 0,
  tokens_out BIGINT NOT NULL DEFAULT 0,
  custo_usd  NUMERIC(10,4) NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Config que o dono edita pelo painel, sem mexer em codigo nem em deploy.
-- Ver src/services/config.js e src/db/migracao-config-painel.sql.
--
-- NAO existe chave para pagamento aqui, e a ausencia e a defesa: quem edita o
-- destinatario do Zelle redireciona o faturamento inteiro. config/pagamento.json
-- continua sendo arquivo, fora do alcance do painel.
CREATE TABLE IF NOT EXISTS config_docs (
  key        TEXT PRIMARY KEY,
  doc        JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by TEXT
);

-- Guarda o documento ANTERIOR: e o que permite desfazer, e responder "quem
-- mudou isso?" depois de um prejuizo.
CREATE TABLE IF NOT EXISTS config_historico (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key        TEXT NOT NULL,
  doc_antes  JSONB,
  mudou_em   TIMESTAMPTZ NOT NULL DEFAULT now(),
  mudou_quem TEXT,
  resumo     TEXT
);

-- Agente Android de impressão. O token bruto nunca é salvo: apenas SHA-256.
-- Vincular um aparelho novo revoga os anteriores, evitando duas impressoras
-- consumirem a mesma fila e permitindo cortar o acesso de um celular roubado.
CREATE TABLE IF NOT EXISTS printer_devices (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  token_hash   TEXT UNIQUE NOT NULL,
  active       BOOLEAN NOT NULL DEFAULT true,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ,
  revoked_at   TIMESTAMPTZ
);

-- Código de pareamento de uso único e validade curta. Só o admin gera pelo
-- WhatsApp; o APK público não contém segredo algum.
CREATE TABLE IF NOT EXISTS printer_pairing_codes (
  id         SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  code_hash  TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by TEXT
);

-- A fila continua sendo a tabela `orders`; NOTIFY é somente a campainha.
-- Se o aviso se perder durante um deploy ou queda de internet, o pedido ainda
-- está `paid` e será encontrado assim que o aplicativo reconectar.
CREATE OR REPLACE FUNCTION notify_printer_order_paid()
RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.status = 'paid' THEN
    PERFORM pg_notify('printer_orders', NEW.id::text);
  ELSIF TG_OP = 'UPDATE' AND NEW.status = 'paid'
    AND OLD.status IS DISTINCT FROM 'paid' THEN
    PERFORM pg_notify('printer_orders', NEW.id::text);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS orders_notify_printer_paid ON orders;
CREATE TRIGGER orders_notify_printer_paid
AFTER INSERT OR UPDATE OF status ON orders
FOR EACH ROW EXECUTE FUNCTION notify_printer_order_paid();

-- Indices
CREATE INDEX IF NOT EXISTS idx_customers_email
  ON customers(email) WHERE email IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_phone_id
  ON orders(phone, id DESC);
CREATE INDEX IF NOT EXISTS idx_orders_phone_delivery_created
  ON orders(phone, created_at DESC) WHERE order_type = 'delivery';
CREATE INDEX IF NOT EXISTS idx_orders_status_created
  ON orders(status, created_at);
CREATE INDEX IF NOT EXISTS idx_orders_print_claim
  ON orders(status, print_claimed_at, created_at) WHERE status = 'paid';
CREATE INDEX IF NOT EXISTS idx_payments_order
  ON payments(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_status
  ON payments(status);
CREATE INDEX IF NOT EXISTS idx_config_hist_key
  ON config_historico(key, mudou_em DESC);

-- Não há RLS nem Data API. Somente o serviço do bot acessa este banco pela
-- rede privada do projeto Railway.
